### ISSUE TITLE
Using the scripts to locally generate and upload albums

### ISSUE THREAD

**Issue by htelsiz** [toehio/s3album#6]
This is not necessarily an issue, but I didn't know where else to ask. Can you explain how these scripts work? Also, do you think it'd be feasible to develop something similar, but in Python?

I'd like to build a small-ish Python utility to loop over large sets of photos and make the contents of each directory an album. I think I'll start with boto3, although I haven't used the AWS SDK for years. 

Let me know what you think. If I end up making a tool, I'd love to add it to this repo.

**Comment by toehio** [comment]
An s3album is directory that contains two sub-directories: `photos/` contains the photos, and `thumbs/` contains the same photos, but resized. There is nothing else (i.e. no metadata files). When viewing the album in your browser, the JS code gets the name of the album, and finds the photos in that album by doing a directory listing of `<album_name>/photos/`.

So, creating an album is pretty straight-forward: make a directory with the name of your album, and add the photos and thumbs. That's what the [mkalbum.sh](https://github.com/toehio/s3album/blob/master/scripts/mkalbum.sh) script does. Running `./mkalbum.sh album_name` finds all the `*.jpg`s in the CWD, and copies them into `album_name/photos` and `album_name/thumbs`, resizing them accordingly. This is all done locally.

Once you have an album directory with the correct structure, you can upload it to your bucket with [upload.sh](https://github.com/toehio/s3album/blob/master/scripts/upload.sh).  This uses [s3cmd](https://github.com/s3tools/s3cmd) and assumes that your albums are stored in `s3://$BUCKET_NAME/albums/albums/`.

I wrote shell scripts for this (and not Python) because it's fairly simple to generate the albums, and mostly consists in creating directories and copying/resizing images with external tools (ImageMagick).

What other features are you looking for?
